### ISSUE TITLE
Expired/invalid apt key

### ISSUE THREAD

**Issue by parak** [DataDog/chef-datadog#521] opened 2018-03-03 01:29 UTC
Hi,

Looks like the current apt key specified in repository.rb is no longer valid, and needs to be replaced with 4B4593018387EEAF.

Thanks!

**Comment by olivielpeau** [comment] 2018-03-05 12:29
Hi @parak, thanks for opening this issue!

That is correct, the key that's currently specified in repository.rb is no longer valid. I've opened #522 to remove its import from the cookbook.

Note that the newer key (`4B4593018387EEAF`) has been imported by this cookbook since v2.7.0.

**Comment by PurrBiscuit** [comment] 2018-03-05 15:47
Hi @olivielpeau - I'm using version 2.7.0 of the datadog cookbook but am still getting an error on the install of the agent from apt-get

```
           ================================================================================
           Error executing action `install` on resource 'apt_package[datadog-agent]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install datadog-agent=1:5.22.1-1 ----
           STDOUT: Reading package lists...
           Building dependency tree...
           Reading state information...
           The following NEW packages will be installed:
             datadog-agent
           0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
           Need to get 93.3 MB of archives.
           After this operation, 308 MB of additional disk space will be used.
           WARNING: The following packages cannot be authenticated!
             datadog-agent
           STDERR: E: There were unauthenticated packages and -y was used without --allow-unauthenticated
           ---- End output of apt-get -q -y install datadog-agent=1:5.22.1-1 ----
           Ran apt-get -q -y install datadog-agent=1:5.22.1-1 returned 100
```

Should this be working with version 2.7.0 of the cookbook or do we need to wait until version 2.14.1 is released with the old key being removed from the `apt_repository` resource?

**Comment by parak** [comment] 2018-03-05 16:03
Hmm, not working for me with the newest commit to master either, apt-get update still complains about NO_PUBKEY 4B4593018387EEAF on a fresh install, and the only key present on the system at the time of the error is still C7A7DA52.

However, if I manually add 4B4593018387EEAF or A2923DFF56EDA6E76E55E492D3A80E30382E94DE, then things work fine.

**Comment by PurrBiscuit** [comment] 2018-03-05 16:25
I can confirm that running `apt-key del C7A7DA52` on the node first before `apt-get -q -y install datadog-agent=1:5.22.1-1` fixes the issue on version 2.7.0 of the cookbook.  It seems like the apt-get install for the agent will error with that `unauthenticated packages` error if both the expired and newer key are present on the node at the same time.

**Comment by olivielpeau** [comment] 2018-03-05 16:40
@parak The `apt_repository` resource should import the correct key on `master`, and in `2.14.0` the previous `execute` resource should import the correct key, so in both cases the newer key should be trusted. It sounds particularly surprising that the old key would still be installed by the `master` cookbook since it's not mentioned anywhere on master. Are you sure this was a fresh environment, and that you were using the master version of the cookbook? Could you provide:

* the chef client logs that are related to the `apt_repository[datadog]` resource
* your Chef version
* the `apt` cookbook version
* your OS/distribution version

@PurrBiscuit both keys should be allowed to be trusted on the system at the same time (the cookbook since version `2.7.0` is actually supposed to make the system trust both). It's surprising that the new key wasn't trusted on the system before you made manual changes. Could you provide the same info as above (or at least part of the info)?

Thanks to you both!

**Comment by PurrBiscuit** [comment] 2018-03-05 17:03
@olivielpeau it looks like a fresh install using version `2.7.0` of the cookbook works fine.  I had been using `2.4.0` on a node and then updated to `2.7.0` and it wasn't working.  All seems ok for me now here.  Thank you.

**Comment by parak** [comment] 2018-03-05 17:19
@olivielpeau Sorry, had some ancient code cruft elsewhere in my runlist that was causing this. All good now, thanks!

**Comment by olivielpeau** [comment] 2018-03-05 17:42
Great, thanks for confirming! I'll go ahead and close the issue then 👍 

The old key will not be installed anymore, starting with v2.14.1 of the cookbook. The new key is of course always installed.

**Closed by olivielpeau** 2018-03-05 17:42 UTC
