### ISSUE TITLE
JMX plugin not formating yml properly

### ISSUE THREAD

**Issue by qgriffith** [DataDog/chef-datadog#337] opened 2016-08-05 17:06 UTC
I am having an issue with the jmx.yml config using chef. It looks like it is not indenting the config properly. There should be two indents for the - include statement. Below is an example of a working config that I did by hand and the one done by chef

```
Working config:
 
instances:
  - host: 127.0.0.1
    name: jmx_instance
    port: 9999
 
init_config:
  conf:
    - include:
        bean: java.lang:type=ClassLoading
        attribute:
          - LoadedClassCount
          - UnloadedClassCount
          - TotalLoadedClassCount
 
Non-working config using the chef recipe:
 
---
instances:
- host: localhost
  port: 9999
  name: jmx_instance
  conf:
  - include:
      bean: java.lang:type=ClassLoading
      attributes:
      - LoadedClassCount
      - UnloadedClassCount
      - TotalLoadedClassCount
```

**Comment by olivielpeau** [comment] 2016-08-08 09:48
@qgriffith Actually the second yaml does have valid indentation, the two indents for the `- include` in `conf` are not mandatory since it denotes an element of a list. You can use an online yaml parser (like http://yaml-online-parser.appspot.com/) if you want to make sure of that.

The only functional difference I can see between your 2 configs is that `host` has been changed from `127.0.0.1` to `localhost`, which could affect jmxfetch's behavior in some environments.

If setting `host` to `127.0.0.1` doesn't work could you give more info on what's not working exactly? (JMXFetch's logs can help, they're located at `/var/log/datadog/jmxfetch.log` on Linux)

I don't think `chef-datadog` is to blame here but I'll keep the issue open until we can determine what the cause of your issue is.

**Comment by qgriffith** [comment] 2016-08-08 17:51
I have set it to 127.0.0.1 and still am having the same issue. When I opened a ticket with datadog they indicated the indents was the problem.

```
---
instances:
- host: 127.0.0.1
  port: 9999
  name: jmx_instance
  conf:
  - include:
      attributes:
      - LoadedClassCount
      - UnloadedClassCount
      - TotalLoadedClassCount
      bean: java.lang:type=ClassLoading
```

If I change the jmx.yml by hand to this, it works

```
---
instances:
- host: 127.0.0.1
  port: 9999
  name: jmx_instance
  conf:
    - include:
        bean: java.lang:type=ClassLoading
        attribute:
          - LoadedClassCount
          - UnloadedClassCount
          - TotalLoadedClassCount

init_config:
# Nothing to configure here
```
Here is the output of jmxfetch

```
2016-08-08 10:40:15,050 | INFO | Connection | Connecting to: service:jmx:rmi:///jndi/rmi://localhost:9999/jmxrmi
2016-08-08 10:40:15,061 | INFO | Instance | Connected to JMX Server at localhost:9999
2016-08-08 10:40:15,254 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=JspMonitor,name=jsp,WebModule=//localhost/host-manager,J2EEApplication=none,J2EEServer=none : javax.management.MBeanAttributeInfo[description=The number of JSPs that have been loaded into a webapp, name=jspCount, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,255 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=JspMonitor,name=jsp,WebModule=//localhost/host-manager,J2EEApplication=none,J2EEServer=none : javax.management.MBeanAttributeInfo[description=The number of JSPs that have been reloaded, name=jspReloadCount, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,255 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=JspMonitor,name=jsp,WebModule=//localhost/host-manager,J2EEApplication=none,J2EEServer=none : javax.management.MBeanAttributeInfo[description=Type of the modeled resource. Can be set only once, name=modelerType, type=java.lang.String, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,287 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute spareNotFoundEntries, name=spareNotFoundEntries, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,287 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute hitsCount, name=hitsCount, type=long, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,287 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute accessCount, name=accessCount, type=long, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,287 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute desiredEntryAccessRatio, name=desiredEntryAccessRatio, type=long, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,288 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Type of the modeled resource. Can be set only once, name=modelerType, type=java.lang.String, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,288 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute cacheSize, name=cacheSize, type=int, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,288 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute maxAllocateIterations, name=maxAllocateIterations, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,288 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/ : javax.management.MBeanAttributeInfo[description=Introspected attribute cacheMaxSize, name=cacheMaxSize, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,420 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute spareNotFoundEntries, name=spareNotFoundEntries, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,421 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute hitsCount, name=hitsCount, type=long, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,421 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute accessCount, name=accessCount, type=long, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,422 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute desiredEntryAccessRatio, name=desiredEntryAccessRatio, type=long, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,422 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Type of the modeled resource. Can be set only once, name=modelerType, type=java.lang.String, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,422 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute cacheSize, name=cacheSize, type=int, read-only, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,423 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute maxAllocateIterations, name=maxAllocateIterations, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,423 | ERROR| Instance | Error while trying to match attributeInfo configuration with the Attribute: Catalina:type=Cache,host=localhost,path=/host-manager : javax.management.MBeanAttributeInfo[description=Introspected attribute cacheMaxSize, name=cacheMaxSize, type=int, read/write, descriptor={}]
java.lang.ClassCastException
2016-08-08 10:40:15,425 | INFO | Instance | Found 19 matching attributes
2016-08-08 10:40:30,456 | INFO | App | Instance jmx_instance is sending 13 metrics to the metrics reporter during collection #3
2016-08-08 10:40:30,512 | INFO | App | Instance tomcat is sending 25 metrics to the metrics reporter during collection #3
2016-08-08 10:40:45,549 | INFO | App | Instance jmx_instance is sending 13 metrics to the metrics reporter during collection #4
2016-08-08 10:40:45,610 | INFO | App | Instance tomcat is sending 25 metrics to the metrics reporter during collection #4
2016-08-08 10:41:00,648 | INFO | App | Instance jmx_instance is sending 13 metrics to the metrics reporter during collection #5
2016-08-08 10:41:00,648 | INFO | App | Next collections will be logged only every 10 collections.
2016-08-08 10:41:00,700 | INFO | App | Instance tomcat is sending 25 metrics to the metrics reporter during collection #5
2016-08-08 10:41:00,700 | INFO | App | Next collections will be logged only every 10 collections.
2016-08-08 10:42:16,041 | INFO | App | Instance jmx_instance is sending 13 metrics to the metrics reporter during collection #10
2016-08-08 10:42:16,084 | INFO | App | Instance tomcat is sending 25 metrics to the metrics reporter during collection #10
```

**Comment by qgriffith** [comment] 2016-08-08 17:56
Wait i see the issue. I had attribute**s** in the chef recipe and not attribute

**Comment by olivielpeau** [comment] 2016-08-09 08:43
Good catch! I'll go ahead and close this issue then, feel free to re-open it if needed

**Closed by olivielpeau** 2016-08-09 08:43 UTC
