### ISSUE TITLE
dd-agent recipe reliably fails to start service

### ISSUE THREAD

**Issue by aprice** [DataDog/chef-datadog#514] opened 2018-02-21 16:11 UTC
We are using Chef 13.5.3 with the datadog cookbook to install the Datadog agent on Windows Server 2016 EC2 instances. Every time the recipe runs, it causes the Chef run to fail with the following error:

`windows_service[datadog-agent] (datadog::dd-agent line 105) had an error: SystemCallError: A stop control has been sent to a service that other running services are dependent on. - ControlService: A stop control has been sent to a service that other running services are dependent on.`

It appears that because DD can't manage to monitor a server with a single agent, it needs to restart it's many services in some specific order, and that's not the order the recipe does it in.

**Comment by smastrorocco** [comment] 2018-02-22 17:10
Seeing the same issue, Windows Server 2012 R2, chef-client v13.6.4

**Comment by olivielpeau** [comment] 2018-03-06 18:02
Should be fixed by https://github.com/DataDog/chef-datadog/pull/520

**Comment by olivielpeau** [comment] 2018-03-21 18:02
#520 was released in `2.15.0`, I'll go ahead and close the issue as resolved, but feel free to comment/re-open if you're the issue isn't fixed for you, thanks!

**Closed by olivielpeau** 2018-03-21 18:02 UTC
