### ISSUE TITLE
Windows cookbook version recommendation

### ISSUE THREAD

**Issue by mlcooper** [DataDog/chef-datadog#439] opened 2017-05-31 20:13 UTC
With the release of 2.10.1, is this statement in the README still valid, or will they work if you jump to depending on 3.x of the `windows` cookbook?
```
With Chef >= 12.6 and the windows cookbook >= 1.39.0, Agent upgrades are known to fail. For Chef>=12.6 users on Windows, we recommend pinning the windows cookbook to a lower version (~> 1.38.0 for instance).
```

**Comment by olivielpeau** [comment] 2017-05-31 23:57
Hi @mlcooper!

This statement is still valid unfortunately. On Windows, if you're using `Chef >= 12.6` and need to use `windows >= 1.39`, `3.0` included, you'll have to use the `remove-dd-agent` recipe before upgrading the agent.

The present cookbook tries to work around multiple edge cases caused by the very inconsistent behavior of the `windows_package` resource depending on the version of Chef (between 12.0 and 12.6) and the version of the `windows` cookbook.

I think the only way to solve this once and for all is to drop support for Chef<=12.6 on Windows. That'll allow using the core resources of Chef only (and drop the dependency on `windows`), and use a `windows_package` resource that just "works".

This will be part of the next major release of the cookbook.

**Comment by mlcooper** [comment] 2017-06-01 13:04
I think that's a great idea to ultimately drop the dependency on the `windows` cookbook.  

Since support for Ruby v2.1 was dropped on April 1, 2017, the earliest Chef client that runs a supported version of Ruby is now v12.14.60, so I think you can certainly make the case for dropping support for Chef <= 12.6.

**Closed** 2023-01-20 17:23 UTC
